In [116]:
import pandas as pd
import numpy as np
data = pd.read_csv('data_flats.csv',sep=";")
data.head()

,id,full_sq,life_sq,floor,sub_area,preschool_quota,preschool_education_centers_raion,school_quota,school_education_centers_raion,school_education_centers_top_20_raion,...,shopping_centers_km,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,theater_km,museum_km,ecology,price_doc
0,1,43,27.0,4.0,Bibirevo,5001.0,5,11065.0,5,0,...,0.648488,0.637189,0.947962,0.177975,0.625783,0.628187,14.053047,7.389498,good,5850000
1,2,34,19.0,3.0,Nagatinskij Zaton,3119.0,5,6237.0,8,0,...,0.519311,0.688796,1.072315,0.273345,0.967821,0.471447,6.829889,0.709260,excellent,6000000
2,3,43,29.0,2.0,Tekstil'shhiki,1463.0,4,5580.0,7,0,...,1.486533,1.543049,0.391957,0.158072,3.178751,0.755946,4.273200,3.156423,poor,5700000
3,4,89,50.0,9.0,Mitino,6839.0,9,17063.0,10,0,...,0.599914,0.934273,0.892674,0.236455,1.031777,1.561505,16.990677,16.041521,good,13100000
4,5,77,77.0,4.0,Basmannoe,3240.0,7,7770.0,9,0,...,0.429052,0.077901,0.810801,0.376838,0.378756,0.121681,1.112486,1.800125,excellent,16331452

In [117]:
data

,id,full_sq,life_sq,floor,sub_area,preschool_quota,preschool_education_centers_raion,school_quota,school_education_centers_raion,school_education_centers_top_20_raion,...,shopping_centers_km,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,theater_km,museum_km,ecology,price_doc
0,1,43,27.0,4.0,Bibirevo,5001.0,5,11065.0,5,0,...,0.648488,0.637189,0.947962,0.177975,0.625783,0.628187,14.053047,7.389498,good,5850000
1,2,34,19.0,3.0,Nagatinskij Zaton,3119.0,5,6237.0,8,0,...,0.519311,0.688796,1.072315,0.273345,0.967821,0.471447,6.829889,0.709260,excellent,6000000
2,3,43,29.0,2.0,Tekstil'shhiki,1463.0,4,5580.0,7,0,...,1.486533,1.543049,0.391957,0.158072,3.178751,0.755946,4.273200,3.156423,poor,5700000
3,4,89,50.0,9.0,Mitino,6839.0,9,17063.0,10,0,...,0.599914,0.934273,0.892674,0.236455,1.031777,1.561505,16.990677,16.041521,good,13100000
4,5,77,77.0,4.0,Basmannoe,3240.0,7,7770.0,9,0,...,0.429052,0.077901,0.810801,0.376838,0.378756,0.121681,1.112486,1.800125,excellent,16331452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30464,30469,44,27.0,7.0,Otradnoe,5088.0,4,12721.0,4,0,...,0.325885,1.103579,0.167718,0.349899,1.235066,0.612359,7.482165,4.836787,good,7400000
30465,30470,86,59.0,3.0,Tverskoe,1874.0,4,6772.0,4,1,...,0.540003,0.069986,0.086552,0.362681,0.850385,0.310021,0.778428,1.450108,poor,25000000
30466,30471,45,NaN,10.0,Poselenie Vnukovskoe,NaN,0,NaN,0,0,...,1.806570,4.338453,1.339078,1.234235,1.192543,1.186621,13.459593,9.890758,no data,6970959
30467,30472,64,32.0,5.0,Obruchevskoe,2372.0,6,6083.0,8,0,...,1.108672,1.204798,1.340017,0.130667,1.644053,0.476021,2.088193,4.119706,satisfactory,13500000
30468,30473,43,28.0,1.0,Novogireevo,2215.0,4,5824.0,4,0,...,0.224601,2.108265,0.825811,0.378950,0.480531,0.867332,0.688707,0.127867,poor,5600000

In [118]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30469 entries, 0 to 30468
Data columns (total 56 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     30469 non-null  int64
 1   full_sq                                30469 non-null  int64
 2   life_sq                                24086 non-null  float64
 3   floor                                  30302 non-null  float64
 4   sub_area                               30469 non-null  object
 5   preschool_quota                        23781 non-null  float64
 6   preschool_education_centers_raion      30469 non-null  int64
 7   school_quota                           23784 non-null  float64
 8   school_education_centers_raion         30469 non-null  int64
 9   school_education_centers_top_20_raion  30469 non-null  int64
 10  hospital_beds_raion                    16029 non-null  float64
 11  healthcare_centers_raion               30469 non-null  int64
 12  university_top_20_raion                30469 non-null  int64
 13  sport_objects_raion                    30469 non-null  int64
 14  additional_education_raion             30469 non-null  int64
 15  culture_objects_top_25_raion           30469 non-null  int64
 16  shopping_centers_raion                 30469 non-null  int64
 17  office_raion                           30469 non-null  int64
 18  metro_min_avto                         30469 non-null  float64
 19  metro_km_avto                          30469 non-null  float64
 20  metro_min_walk                         30444 non-null  float64
 21  metro_km_walk                          30444 non-null  float64
 22  kindergarten_km                        30469 non-null  float64
 23  school_km                              30469 non-null  float64
 24  park_km                                30469 non-null  float64
 25  green_zone_km                          30469 non-null  float64
 26  industrial_km                          30469 non-null  float64
 27  railroad_station_walk_km               30444 non-null  float64
 28  railroad_station_walk_min              30444 non-null  float64
 29  public_transport_station_km            30469 non-null  float64
 30  public_transport_station_min_walk      30469 non-null  float64
 31  mkad_km                                30469 non-null  float64
 32  ttk_km                                 30469 non-null  float64
 33  sadovoe_km                             30469 non-null  float64
 34  bulvar_ring_km                         30469 non-null  float64
 35  kremlin_km                             30469 non-null  float64
 36  big_market_km                          30469 non-null  float64
 37  market_shop_km                         30469 non-null  float64
 38  fitness_km                             30469 non-null  float64
 39  swim_pool_km                           30469 non-null  float64
 40  ice_rink_km                            30469 non-null  float64
 41  stadium_km                             30469 non-null  float64
 42  basketball_km                          30469 non-null  float64
 43  hospice_morgue_km                      30469 non-null  float64
 44  university_km                          30469 non-null  float64
 45  workplaces_km                          30469 non-null  float64
 46  shopping_centers_km                    30469 non-null  float64
 47  office_km                              30469 non-null  float64
 48  additional_education_km                30469 non-null  float64
 49  preschool_km                           30469 non-null  float64
 50  big_church_km                          30469 non-null  float64
 51  church_synagogue_km                    30469 non-null  float64
 52  theater_km                             30469 non-null  float64
 53  museum_km                              30469 non-null  float64
 54  ecology                                30469 non-null  object
 55  price_doc                              30469 non-null  int64
dtypes: float64(41), int64(13), object(2)
memory usage: 13.0+ MB

In [123]:
data2=data.dropna()

In [120]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30469 entries, 0 to 30468
Data columns (total 56 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   id                                     30469 non-null  int64
 1   full_sq                                30469 non-null  int64
 2   life_sq                                24086 non-null  float64
 3   floor                                  30302 non-null  float64
 4   sub_area                               30469 non-null  object
 5   preschool_quota                        23781 non-null  float64
 6   preschool_education_centers_raion      30469 non-null  int64
 7   school_quota                           23784 non-null  float64
 8   school_education_centers_raion         30469 non-null  int64
 9   school_education_centers_top_20_raion  30469 non-null  int64
 10  hospital_beds_raion                    16029 non-null  float64
 11  healthcare_centers_raion               30469 non-null  int64
 12  university_top_20_raion                30469 non-null  int64
 13  sport_objects_raion                    30469 non-null  int64
 14  additional_education_raion             30469 non-null  int64
 15  culture_objects_top_25_raion           30469 non-null  int64
 16  shopping_centers_raion                 30469 non-null  int64
 17  office_raion                           30469 non-null  int64
 18  metro_min_avto                         30469 non-null  float64
 19  metro_km_avto                          30469 non-null  float64
 20  metro_min_walk                         30444 non-null  float64
 21  metro_km_walk                          30444 non-null  float64
 22  kindergarten_km                        30469 non-null  float64
 23  school_km                              30469 non-null  float64
 24  park_km                                30469 non-null  float64
 25  green_zone_km                          30469 non-null  float64
 26  industrial_km                          30469 non-null  float64
 27  railroad_station_walk_km               30444 non-null  float64
 28  railroad_station_walk_min              30444 non-null  float64
 29  public_transport_station_km            30469 non-null  float64
 30  public_transport_station_min_walk      30469 non-null  float64
 31  mkad_km                                30469 non-null  float64
 32  ttk_km                                 30469 non-null  float64
 33  sadovoe_km                             30469 non-null  float64
 34  bulvar_ring_km                         30469 non-null  float64
 35  kremlin_km                             30469 non-null  float64
 36  big_market_km                          30469 non-null  float64
 37  market_shop_km                         30469 non-null  float64
 38  fitness_km                             30469 non-null  float64
 39  swim_pool_km                           30469 non-null  float64
 40  ice_rink_km                            30469 non-null  float64
 41  stadium_km                             30469 non-null  float64
 42  basketball_km                          30469 non-null  float64
 43  hospice_morgue_km                      30469 non-null  float64
 44  university_km                          30469 non-null  float64
 45  workplaces_km                          30469 non-null  float64
 46  shopping_centers_km                    30469 non-null  float64
 47  office_km                              30469 non-null  float64
 48  additional_education_km                30469 non-null  float64
 49  preschool_km                           30469 non-null  float64
 50  big_church_km                          30469 non-null  float64
 51  church_synagogue_km                    30469 non-null  float64
 52  theater_km                             30469 non-null  float64
 53  museum_km                              30469 non-null  float64
 54  ecology                                30469 non-null  object
 55  price_doc                              30469 non-null  int64
dtypes: float64(41), int64(13), object(2)
memory usage: 13.0+ MB

In [124]:
print(data2.isnull().sum())

id                                       0
full_sq                                  0
life_sq                                  0
floor                                    0
sub_area                                 0
preschool_quota                          0
preschool_education_centers_raion        0
school_quota                             0
school_education_centers_raion           0
school_education_centers_top_20_raion    0
hospital_beds_raion                      0
healthcare_centers_raion                 0
university_top_20_raion                  0
sport_objects_raion                      0
additional_education_raion               0
culture_objects_top_25_raion             0
shopping_centers_raion                   0
office_raion                             0
metro_min_avto                           0
metro_km_avto                            0
metro_min_walk                           0
metro_km_walk                            0
kindergarten_km                          0
school_km                                0
park_km                                  0
green_zone_km                            0
industrial_km                            0
railroad_station_walk_km                 0
railroad_station_walk_min                0
public_transport_station_km              0
public_transport_station_min_walk        0
mkad_km                                  0
ttk_km                                   0
sadovoe_km                               0
bulvar_ring_km                           0
kremlin_km                               0
big_market_km                            0
market_shop_km                           0
fitness_km                               0
swim_pool_km                             0
ice_rink_km                              0
stadium_km                               0
basketball_km                            0
hospice_morgue_km                        0
university_km                            0
workplaces_km                            0
shopping_centers_km                      0
office_km                                0
additional_education_km                  0
preschool_km                             0
big_church_km                            0
church_synagogue_km                      0
theater_km                               0
museum_km                                0
ecology                                  0
price_doc                                0
dtype: int64

In [97]:
print(data.isna().sum())

id                                           0
full_sq                                      0
life_sq                                   6383
floor                                      167
sub_area                                     0
preschool_quota                           6688
preschool_education_centers_raion            0
school_quota                              6685
school_education_centers_raion               0
school_education_centers_top_20_raion        0
hospital_beds_raion                      14440
healthcare_centers_raion                     0
university_top_20_raion                      0
sport_objects_raion                          0
additional_education_raion                   0
culture_objects_top_25_raion                 0
shopping_centers_raion                       0
office_raion                                 0
metro_min_avto                               0
metro_km_avto                                0
metro_min_walk                              25
metro_km_walk                               25
kindergarten_km                              0
school_km                                    0
park_km                                      0
green_zone_km                                0
industrial_km                                0
railroad_station_walk_km                    25
railroad_station_walk_min                   25
public_transport_station_km                  0
public_transport_station_min_walk            0
mkad_km                                      0
ttk_km                                       0
sadovoe_km                                   0
bulvar_ring_km                               0
kremlin_km                                   0
big_market_km                                0
market_shop_km                               0
fitness_km                                   0
swim_pool_km                                 0
ice_rink_km                                  0
stadium_km                                   0
basketball_km                                0
hospice_morgue_km                            0
university_km                                0
workplaces_km                                0
shopping_centers_km                          0
office_km                                    0
additional_education_km                      0
preschool_km                                 0
big_church_km                                0
church_synagogue_km                          0
theater_km                                   0
museum_km                                    0
ecology                                      0
price_doc                                    0
dtype: int64

In [98]:
data['preschool_quota'] = data['preschool_quota'].fillna(0)

In [99]:
print(data)

          id  full_sq  life_sq  floor              sub_area  preschool_quota  \
0          1       43     27.0    4.0              Bibirevo           5001.0
1          2       34     19.0    3.0     Nagatinskij Zaton           3119.0
2          3       43     29.0    2.0        Tekstil'shhiki           1463.0
3          4       89     50.0    9.0                Mitino           6839.0
4          5       77     77.0    4.0             Basmannoe           3240.0
...      ...      ...      ...    ...                   ...              ...
30464  30469       44     27.0    7.0              Otradnoe           5088.0
30465  30470       86     59.0    3.0              Tverskoe           1874.0
30466  30471       45      NaN   10.0  Poselenie Vnukovskoe              0.0
30467  30472       64     32.0    5.0          Obruchevskoe           2372.0
30468  30473       43     28.0    1.0           Novogireevo           2215.0

       preschool_education_centers_raion  school_quota  \
0                                      5       11065.0
1                                      5        6237.0
2                                      4        5580.0
3                                      9       17063.0
4                                      7        7770.0
...                                  ...           ...
30464                                  4       12721.0
30465                                  4        6772.0
30466                                  0           NaN
30467                                  6        6083.0
30468                                  4        5824.0

       school_education_centers_raion  school_education_centers_top_20_raion  \
0                                   5                                      0
1                                   8                                      0
2                                   7                                      0
3                                  10                                      0
4                                   9                                      0
...                               ...                                    ...
30464                               4                                      0
30465                               4                                      1
30466                               0                                      0
30467                               8                                      0
30468                               4                                      0

       ...  shopping_centers_km  office_km  additional_education_km  \
0      ...             0.648488   0.637189                 0.947962
1      ...             0.519311   0.688796                 1.072315
2      ...             1.486533   1.543049                 0.391957
3      ...             0.599914   0.934273                 0.892674
4      ...             0.429052   0.077901                 0.810801
...    ...                  ...        ...                      ...
30464  ...             0.325885   1.103579                 0.167718
30465  ...             0.540003   0.069986                 0.086552
30466  ...             1.806570   4.338453                 1.339078
30467  ...             1.108672   1.204798                 1.340017
30468  ...             0.224601   2.108265                 0.825811

       preschool_km  big_church_km  church_synagogue_km  theater_km  \
0          0.177975       0.625783             0.628187   14.053047
1          0.273345       0.967821             0.471447    6.829889
2          0.158072       3.178751             0.755946    4.273200
3          0.236455       1.031777             1.561505   16.990677
4          0.376838       0.378756             0.121681    1.112486
...             ...            ...                  ...         ...
30464      0.349899       1.235066             0.612359    7.482165
30465      0.362681       0.850385             0.310021    0.778428
30466      1.234235       1.192543             1.186621   13.459593
30467      0.130667       1.644053             0.476021    2.088193
30468      0.378950       0.480531             0.867332    0.688707

       museum_km       ecology  price_doc
0       7.389498          good    5850000
1       0.709260     excellent    6000000
2       3.156423          poor    5700000
3      16.041521          good   13100000
4       1.800125     excellent   16331452
...          ...           ...        ...
30464   4.836787          good    7400000
30465   1.450108          poor   25000000
30466   9.890758       no data    6970959
30467   4.119706  satisfactory   13500000
30468   0.127867          poor    5600000

[30469 rows x 56 columns]

In [100]:
print(data)

          id  full_sq  life_sq  floor              sub_area  preschool_quota  \
0          1       43     27.0    4.0              Bibirevo           5001.0
1          2       34     19.0    3.0     Nagatinskij Zaton           3119.0
2          3       43     29.0    2.0        Tekstil'shhiki           1463.0
3          4       89     50.0    9.0                Mitino           6839.0
4          5       77     77.0    4.0             Basmannoe           3240.0
...      ...      ...      ...    ...                   ...              ...
30464  30469       44     27.0    7.0              Otradnoe           5088.0
30465  30470       86     59.0    3.0              Tverskoe           1874.0
30466  30471       45      NaN   10.0  Poselenie Vnukovskoe              0.0
30467  30472       64     32.0    5.0          Obruchevskoe           2372.0
30468  30473       43     28.0    1.0           Novogireevo           2215.0

       preschool_education_centers_raion  school_quota  \
0                                      5       11065.0
1                                      5        6237.0
2                                      4        5580.0
3                                      9       17063.0
4                                      7        7770.0
...                                  ...           ...
30464                                  4       12721.0
30465                                  4        6772.0
30466                                  0           NaN
30467                                  6        6083.0
30468                                  4        5824.0

       school_education_centers_raion  school_education_centers_top_20_raion  \
0                                   5                                      0
1                                   8                                      0
2                                   7                                      0
3                                  10                                      0
4                                   9                                      0
...                               ...                                    ...
30464                               4                                      0
30465                               4                                      1
30466                               0                                      0
30467                               8                                      0
30468                               4                                      0

       ...  shopping_centers_km  office_km  additional_education_km  \
0      ...             0.648488   0.637189                 0.947962
1      ...             0.519311   0.688796                 1.072315
2      ...             1.486533   1.543049                 0.391957
3      ...             0.599914   0.934273                 0.892674
4      ...             0.429052   0.077901                 0.810801
...    ...                  ...        ...                      ...
30464  ...             0.325885   1.103579                 0.167718
30465  ...             0.540003   0.069986                 0.086552
30466  ...             1.806570   4.338453                 1.339078
30467  ...             1.108672   1.204798                 1.340017
30468  ...             0.224601   2.108265                 0.825811

       preschool_km  big_church_km  church_synagogue_km  theater_km  \
0          0.177975       0.625783             0.628187   14.053047
1          0.273345       0.967821             0.471447    6.829889
2          0.158072       3.178751             0.755946    4.273200
3          0.236455       1.031777             1.561505   16.990677
4          0.376838       0.378756             0.121681    1.112486
...             ...            ...                  ...         ...
30464      0.349899       1.235066             0.612359    7.482165
30465      0.362681       0.850385             0.310021    0.778428
30466      1.234235       1.192543             1.186621   13.459593
30467      0.130667       1.644053             0.476021    2.088193
30468      0.378950       0.480531             0.867332    0.688707

       museum_km       ecology  price_doc
0       7.389498          good    5850000
1       0.709260     excellent    6000000
2       3.156423          poor    5700000
3      16.041521          good   13100000
4       1.800125     excellent   16331452
...          ...           ...        ...
30464   4.836787          good    7400000
30465   1.450108          poor   25000000
30466   9.890758       no data    6970959
30467   4.119706  satisfactory   13500000
30468   0.127867          poor    5600000

[30469 rows x 56 columns]

In [101]:
data.dropna(subset = ['life_sq', 'floor', 'preschool_quota'], inplace = True)

In [102]:
print(data)

          id  full_sq  life_sq  floor           sub_area  preschool_quota  \
0          1       43     27.0    4.0           Bibirevo           5001.0
1          2       34     19.0    3.0  Nagatinskij Zaton           3119.0
2          3       43     29.0    2.0     Tekstil'shhiki           1463.0
3          4       89     50.0    9.0             Mitino           6839.0
4          5       77     77.0    4.0          Basmannoe           3240.0
...      ...      ...      ...    ...                ...              ...
30462  30467       56     51.0   19.0           Sviblovo           2057.0
30464  30469       44     27.0    7.0           Otradnoe           5088.0
30465  30470       86     59.0    3.0           Tverskoe           1874.0
30467  30472       64     32.0    5.0       Obruchevskoe           2372.0
30468  30473       43     28.0    1.0        Novogireevo           2215.0

       preschool_education_centers_raion  school_quota  \
0                                      5       11065.0
1                                      5        6237.0
2                                      4        5580.0
3                                      9       17063.0
4                                      7        7770.0
...                                  ...           ...
30462                                  1        3741.0
30464                                  4       12721.0
30465                                  4        6772.0
30467                                  6        6083.0
30468                                  4        5824.0

       school_education_centers_raion  school_education_centers_top_20_raion  \
0                                   5                                      0
1                                   8                                      0
2                                   7                                      0
3                                  10                                      0
4                                   9                                      0
...                               ...                                    ...
30462                               2                                      0
30464                               4                                      0
30465                               4                                      1
30467                               8                                      0
30468                               4                                      0

       ...  shopping_centers_km  office_km  additional_education_km  \
0      ...             0.648488   0.637189                 0.947962
1      ...             0.519311   0.688796                 1.072315
2      ...             1.486533   1.543049                 0.391957
3      ...             0.599914   0.934273                 0.892674
4      ...             0.429052   0.077901                 0.810801
...    ...                  ...        ...                      ...
30462  ...             0.187828   0.969990                 0.510751
30464  ...             0.325885   1.103579                 0.167718
30465  ...             0.540003   0.069986                 0.086552
30467  ...             1.108672   1.204798                 1.340017
30468  ...             0.224601   2.108265                 0.825811

       preschool_km  big_church_km  church_synagogue_km  theater_km  \
0          0.177975       0.625783             0.628187   14.053047
1          0.273345       0.967821             0.471447    6.829889
2          0.158072       3.178751             0.755946    4.273200
3          0.236455       1.031777             1.561505   16.990677
4          0.376838       0.378756             0.121681    1.112486
...             ...            ...                  ...         ...
30462      0.566309       1.261711             0.532268    3.672399
30464      0.349899       1.235066             0.612359    7.482165
30465      0.362681       0.850385             0.310021    0.778428
30467      0.130667       1.644053             0.476021    2.088193
30468      0.378950       0.480531             0.867332    0.688707

       museum_km       ecology  price_doc
0       7.389498          good    5850000
1       0.709260     excellent    6000000
2       3.156423          poor    5700000
3      16.041521          good   13100000
4       1.800125     excellent   16331452
...          ...           ...        ...
30462   2.988268          poor   10262010
30464   4.836787          good    7400000
30465   1.450108          poor   25000000
30467   4.119706  satisfactory   13500000
30468   0.127867          poor    5600000

[23946 rows x 56 columns]

In [103]:
data.dropna(axis = 'columns', inplace = True)

In [104]:
data

,id,full_sq,life_sq,floor,sub_area,preschool_quota,preschool_education_centers_raion,school_education_centers_raion,school_education_centers_top_20_raion,healthcare_centers_raion,...,shopping_centers_km,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,theater_km,museum_km,ecology,price_doc
0,1,43,27.0,4.0,Bibirevo,5001.0,5,5,0,1,...,0.648488,0.637189,0.947962,0.177975,0.625783,0.628187,14.053047,7.389498,good,5850000
1,2,34,19.0,3.0,Nagatinskij Zaton,3119.0,5,8,0,1,...,0.519311,0.688796,1.072315,0.273345,0.967821,0.471447,6.829889,0.709260,excellent,6000000
2,3,43,29.0,2.0,Tekstil'shhiki,1463.0,4,7,0,1,...,1.486533,1.543049,0.391957,0.158072,3.178751,0.755946,4.273200,3.156423,poor,5700000
3,4,89,50.0,9.0,Mitino,6839.0,9,10,0,1,...,0.599914,0.934273,0.892674,0.236455,1.031777,1.561505,16.990677,16.041521,good,13100000
4,5,77,77.0,4.0,Basmannoe,3240.0,7,9,0,4,...,0.429052,0.077901,0.810801,0.376838,0.378756,0.121681,1.112486,1.800125,excellent,16331452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30462,30467,56,51.0,19.0,Sviblovo,2057.0,1,2,0,1,...,0.187828,0.969990,0.510751,0.566309,1.261711,0.532268,3.672399,2.988268,poor,10262010
30464,30469,44,27.0,7.0,Otradnoe,5088.0,4,4,0,1,...,0.325885,1.103579,0.167718,0.349899,1.235066,0.612359,7.482165,4.836787,good,7400000
30465,30470,86,59.0,3.0,Tverskoe,1874.0,4,4,1,3,...,0.540003,0.069986,0.086552,0.362681,0.850385,0.310021,0.778428,1.450108,poor,25000000
30467,30472,64,32.0,5.0,Obruchevskoe,2372.0,6,8,0,2,...,1.108672,1.204798,1.340017,0.130667,1.644053,0.476021,2.088193,4.119706,satisfactory,13500000
30468,30473,43,28.0,1.0,Novogireevo,2215.0,4,4,0,2,...,0.224601,2.108265,0.825811,0.378950,0.480531,0.867332,0.688707,0.127867,poor,5600000

In [113]:
data.dropna()

,id,full_sq,life_sq,floor,sub_area,preschool_quota,preschool_education_centers_raion,school_education_centers_raion,school_education_centers_top_20_raion,healthcare_centers_raion,...,shopping_centers_km,office_km,additional_education_km,preschool_km,big_church_km,church_synagogue_km,theater_km,museum_km,ecology,price_doc
0,1,43,27.0,4.0,Bibirevo,5001.0,5,5,0,1,...,0.648488,0.637189,0.947962,0.177975,0.625783,0.628187,14.053047,7.389498,good,5850000
1,2,34,19.0,3.0,Nagatinskij Zaton,3119.0,5,8,0,1,...,0.519311,0.688796,1.072315,0.273345,0.967821,0.471447,6.829889,0.709260,excellent,6000000
2,3,43,29.0,2.0,Tekstil'shhiki,1463.0,4,7,0,1,...,1.486533,1.543049,0.391957,0.158072,3.178751,0.755946,4.273200,3.156423,poor,5700000
3,4,89,50.0,9.0,Mitino,6839.0,9,10,0,1,...,0.599914,0.934273,0.892674,0.236455,1.031777,1.561505,16.990677,16.041521,good,13100000
4,5,77,77.0,4.0,Basmannoe,3240.0,7,9,0,4,...,0.429052,0.077901,0.810801,0.376838,0.378756,0.121681,1.112486,1.800125,excellent,16331452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30462,30467,56,51.0,19.0,Sviblovo,2057.0,1,2,0,1,...,0.187828,0.969990,0.510751,0.566309,1.261711,0.532268,3.672399,2.988268,poor,10262010
30464,30469,44,27.0,7.0,Otradnoe,5088.0,4,4,0,1,...,0.325885,1.103579,0.167718,0.349899,1.235066,0.612359,7.482165,4.836787,good,7400000
30465,30470,86,59.0,3.0,Tverskoe,1874.0,4,4,1,3,...,0.540003,0.069986,0.086552,0.362681,0.850385,0.310021,0.778428,1.450108,poor,25000000
30467,30472,64,32.0,5.0,Obruchevskoe,2372.0,6,8,0,2,...,1.108672,1.204798,1.340017,0.130667,1.644053,0.476021,2.088193,4.119706,satisfactory,13500000
30468,30473,43,28.0,1.0,Novogireevo,2215.0,4,4,0,2,...,0.224601,2.108265,0.825811,0.378950,0.480531,0.867332,0.688707,0.127867,poor,5600000

In [114]:
print(data)

          id  full_sq  life_sq  floor           sub_area  preschool_quota  \
0          1       43     27.0    4.0           Bibirevo           5001.0
1          2       34     19.0    3.0  Nagatinskij Zaton           3119.0
2          3       43     29.0    2.0     Tekstil'shhiki           1463.0
3          4       89     50.0    9.0             Mitino           6839.0
4          5       77     77.0    4.0          Basmannoe           3240.0
...      ...      ...      ...    ...                ...              ...
30462  30467       56     51.0   19.0           Sviblovo           2057.0
30464  30469       44     27.0    7.0           Otradnoe           5088.0
30465  30470       86     59.0    3.0           Tverskoe           1874.0
30467  30472       64     32.0    5.0       Obruchevskoe           2372.0
30468  30473       43     28.0    1.0        Novogireevo           2215.0

       preschool_education_centers_raion  school_education_centers_raion  \
0                                      5                               5
1                                      5                               8
2                                      4                               7
3                                      9                              10
4                                      7                               9
...                                  ...                             ...
30462                                  1                               2
30464                                  4                               4
30465                                  4                               4
30467                                  6                               8
30468                                  4                               4

       school_education_centers_top_20_raion  healthcare_centers_raion  ...  \
0                                          0                         1  ...
1                                          0                         1  ...
2                                          0                         1  ...
3                                          0                         1  ...
4                                          0                         4  ...
...                                      ...                       ...  ...
30462                                      0                         1  ...
30464                                      0                         1  ...
30465                                      1                         3  ...
30467                                      0                         2  ...
30468                                      0                         2  ...

       shopping_centers_km  office_km  additional_education_km  preschool_km  \
0                 0.648488   0.637189                 0.947962      0.177975
1                 0.519311   0.688796                 1.072315      0.273345
2                 1.486533   1.543049                 0.391957      0.158072
3                 0.599914   0.934273                 0.892674      0.236455
4                 0.429052   0.077901                 0.810801      0.376838
...                    ...        ...                      ...           ...
30462             0.187828   0.969990                 0.510751      0.566309
30464             0.325885   1.103579                 0.167718      0.349899
30465             0.540003   0.069986                 0.086552      0.362681
30467             1.108672   1.204798                 1.340017      0.130667
30468             0.224601   2.108265                 0.825811      0.378950

       big_church_km  church_synagogue_km  theater_km  museum_km  \
0           0.625783             0.628187   14.053047   7.389498
1           0.967821             0.471447    6.829889   0.709260
2           3.178751             0.755946    4.273200   3.156423
3           1.031777             1.561505   16.990677  16.041521
4           0.378756             0.121681    1.112486   1.800125
...              ...                  ...         ...        ...
30462       1.261711             0.532268    3.672399   2.988268
30464       1.235066             0.612359    7.482165   4.836787
30465       0.850385             0.310021    0.778428   1.450108
30467       1.644053             0.476021    2.088193   4.119706
30468       0.480531             0.867332    0.688707   0.127867

            ecology  price_doc
0              good    5850000
1         excellent    6000000
2              poor    5700000
3              good   13100000
4         excellent   16331452
...             ...        ...
30462          poor   10262010
30464          good    7400000
30465          poor   25000000
30467  satisfactory   13500000
30468          poor    5600000

[23946 rows x 50 columns]